name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ 1.73.0 ]

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      run: |
        rustup update ${{ matrix.rust }} --no-self-update
        rustup default ${{ matrix.rust }}
        rustup component add rustfmt
        rustup component add clippy

    - name: Check Format
      run: cargo fmt --all -- --check

    - name: Clippy
      run: cargo clippy --tests --benches -- -D clippy::all -D warnings

    - name: Build
      run: cargo build --verbose
